### ISSUE TITLE
jd.bukkit.org Links are broken

### ISSUE THREAD

**Issue by twizmwazin** [OvercastNetwork/docs.oc.tc#186]
As jd.bukkit.org is offline, all the links are broken.

**Comment by kev3200** [comment]
Why are the links broken? I'm glad to know it's not just me but reason would be nice.

**Comment by khazhyk** [comment]
jd.bukkt.org is offline

**Comment by kev3200** [comment]
Got that. why? :P

**Comment by khazhyk** [comment]
Pretty sure Curse shut it down

**Comment by mrapple** [comment]
It was an accident https://bukkit.org/threads/javadocs-down.341615/#post-3019402

**Comment by twizmwazin** [comment]
@mrapple However, it has been over a week since that statement was made, and there has been no update on it since.

**Comment by mrapple** [comment]
Doesn't mean it wasn't an accident, they're just slow

**Comment by twizmwazin** [comment]
@mrapple Or disinterested in putting them back up.

**Comment by khazhyk** [comment]
ah that's good to know, guess i shouldn't trust the rumor mill

**Comment by mrapple** [comment]
@twizmwazin What's with the hostility towards Curse? They're probably working on it, just let it be

**Comment by twizmwazin** [comment]
@mrapple After reading [this post by EvilSeph] (http://bukkit.org/threads/applaud-what-you-did-right-dont-wallow-in-what-your-predecessor-did-wrong.322035/), I've had a somewhat negative view on Curse.

**Comment by mrapple** [comment]
I see no reason to not trust the post on the bukkit forums. Just let it be

**Comment by kev3200** [comment]
Maybe they are updating it or something... :/ Can't just jump to conclusions :)
