### ISSUE TITLE
Current map proto not displaying on Protocol Versions page (modules/proto)

### ISSUE THREAD

**Issue by matic0basle** [OvercastNetwork/docs.oc.tc#190]
On all sites on the modules part the "Current map proto" well displays the current map proto and a link leading to the protocol versions page except the Protocol Versions page.

Not sure whats causing this thats why its an issue not a PR but could have to do with the protocol versions page not being in the modules sidebar.

![](http://i.gyazo.com/9dc7b66922cc9c9725e86f268e8344f2.png)

![](http://i.gyazo.com/c1e461d3a9af1c2e7038269f3d7d1e00.png)

**Comment by mrapple** [comment]
Yeah, we noticed this a few days ago. No clue what's causing it or how to fix it.

**Comment by nixter1029** [comment]
Yeah I was confused by this because it doesn't do it locally.

**Comment by AnthonyTag** [comment]
it's been fixed
