### ISSUE TITLE
FFA module info

### ISSUE THREAD

**Issue by stormer1267** [OvercastNetwork/docs.oc.tc#202]
so, when I was making a map for the map contest it was really hard to find how to add FFA to your map. I  ended up asking a mapdev how to do it. 

I think it would be good if the FFA module would be added because it is basically missing.

**Comment by mitchiiii** [comment]
The players module is [documented here](https://docs.oc.tc/modules/players).

**Comment by elephantLocator** [comment]
Just to note this has been clarified in 118007fd7ad16b7e4bbccd517f15230a3486c4aa.
