### ISSUE TITLE
Side Quick Links don't match with Pages Titles

### ISSUE THREAD

**Issue by xXFracXx** [OvercastNetwork/docs.oc.tc#210]
The issue's title might not be clear, basically the quick links provided (the ones in red boxes in the below screenshots) don't match up with their corresponding titles on the same page, they are actually incorrect and match up with Titles from other pages. I hope the screen shots do a better job of explaining:

<img width="1920" alt="screen shot 2016-05-12 at 10 38 06 am" src="https://cloud.githubusercontent.com/assets/4745792/15204748/7c72443a-182e-11e6-99cc-0f401de4fcb7.png">

<img width="1920" alt="screen shot 2016-05-12 at 10 37 50 am" src="https://cloud.githubusercontent.com/assets/4745792/15204754/8cdf35da-182e-11e6-8b36-210ba60a0ac3.png">

**Comment by McSpider** [comment]
This was fixed in 1af78fcd2b5abfa82869221313faa4417e7ebed5 but has not yet been deployed.

**Comment by xXFracXx** [comment]
alright, cool 👍
